compute_environment: LOCAL_MACHINE
distributed_type: TPU
mixed_precision: "no"
use_cpu: false
num_processes: 4
machine_rank: 0
num_machines: 1
rdzv_backend: static
same_network: true
main_training_function: main
deepspeed_config: {}
fsdp_config: {}
megatron_lm_config: {}
downcast_bf16: false
tpu_use_cluster: false
tpu_use_sudo: false
tpu_env: []
dynamo_config: {}
